- Matched-Audience-Upload-API-Quickstart-Guide.md
- Reporting-API-Quickstart-Guide.md
- Schedule-Report-API-Quickstart-Guide.md
- Upload-Creative-and-Create-a-Campaign-API-Quickstart-Guide.md
- index.md
- user-profile-guidelines.md
Add user and profile management guidelines page
Add links and guidelines subsection to index
> Creates User&Profile Guidelines page

- Reporting-API-Quickstart-Guide.md
- Schedule-Report-API-Quickstart-Guide.md
- Upload-Creative-and-Create-a-Campaign-API-Quickstart-Guide.md
- User-Profile-Guidelines.md
- index.md
Add "Get List of Users" section
Update all files for minor style changes:
-remove headings from response samples
-[required] consistency
> Updates User-Profile-Guidelines.md

- Schedule-Report-API-Quickstart-Guide.md
- index.md
Changes phrasing: Schedule a Report
> Update Report Scheduling

- Bid-Model-API-Guidelines.md
- Campaign-API-Guidelines.md
- Matched-Audience-Upload-API-Quickstart-Guide.md
- Reporting-API-Quickstart-Guide.md
- Schedule-Report-API-Quickstart-Guide.md
- Upload-Creative-and-Create-a-Campaign-API-Quickstart-Guide.md
- User-Profile-Guidelines.md
- index.md
Create Campaign API Guidelines
Removes all heading syntax from Header Parameters and Request Body Schema sections, changes to bold
Updates phrasing in Bid Model Guidelines: Include/Exclude
Removes `whiteList` and `blackList` properties
> Create Campaign API Guidelines Page

- Authentication-Quickstart-Guide.md
- index.md
Adds Signup and Authentication Quickstart Guide
Adds link to Authenticaion Quickstart guide to index.md
> Authentication quickstart guide

- Reports-API-Guidelines.md
- index.md
Creates Reports API Guidelines page
Adds links to index.md
> Reports API Guidelines

- Conversion-API-Guidelines.md
- index.md
Creates API Guidelines Page
Adds links to index.md
> Conversion api guidelines

- docs/Guidelines/Assets-API-Guidelines.mdx
- docs/Guidelines/Bid-Model-API-Guidelines.mdx
- docs/Guidelines/Campaign-API-Guidelines.mdx
- docs/Guidelines/Conversion-API-Guidelines.mdx
- docs/Guidelines/Insights-API-Guidelines.mdx
- docs/Guidelines/Master-API-Guidelines.mdx
- docs/Guidelines/Reports-API-Guidelines.mdx
- docs/Guidelines/User-Profile-Guidelines.mdx
- docs/Guidelines/Workspace-Guidelines.mdx
- docs/Quickstart Guides/Authentication-Quickstart-Guide.mdx
- docs/Quickstart Guides/Matched-Audience-Upload-API-Quickstart-Guide.mdx
- docs/Quickstart Guides/Reporting-API-Quickstart-Guide.mdx
- docs/Quickstart Guides/Schedule-Report-API-Quickstart-Guide.mdx
- docs/Quickstart Guides/Upload-Creative-and-Create-a-Campaign-API-Quickstart-Guide.mdx
- docs/intro.md
Adds typescript examples to all Quickstart Guides
Updates descriptions and formatting
> Quickstart updates

- docs/Guidelines/Reports-API-Guidelines.mdx
- docs/Quickstart Guides/Matched-Audience-Upload-API-Quickstart-Guide.mdx
- docs/Quickstart Guides/Reporting-API-Quickstart-Guide.mdx
- docs/Quickstart Guides/Schedule-Report-API-Quickstart-Guide.mdx
- docs/Quickstart Guides/Upload-Creative-and-Create-a-Campaign-API-Quickstart-Guide.mdx
- docusaurus.config.js
> Fixes links

- docs/Quickstart Guides/Matched-Audience-Upload-API-Quickstart-Guide.mdx
- docs/Quickstart Guides/Upload-Creative-and-Create-a-Campaign-API-Quickstart-Guide.mdx
> Link fix 2

- docusaurus.config.js
> Ignore broken links

- docs/Getting Started/Typescript-Prerequisites.mdx
- docs/Getting Started/index.mdx
- sidebars.js
Adds sidebar to index pages, TS page
Adds TS card to Getting Started index page
> Sidebar update

- sidebars.js
- src/css/custom.css
Updates method badges color style
Adds method badges to sidebar items
> Method Badges

- package-lock.json
- package.json
removes unnecessary npm packages
> npm packages

- .github/workflows/deploy.yml
> Revert "Peer dependencies fix"

- docs/Getting Started/Before-You-Begin.mdx
- docs/Getting Started/REST-API-Reference.mdx
- docs/Getting Started/Typescript-Prerequisites.mdx
- docs/Guidelines/Campaign-API-Guidelines.mdx
- docs/Guidelines/Reports-API-Guidelines.mdx
- docs/Guidelines/User-Profile-Guidelines.mdx
- docs/Quickstart Guides/Authentication-Quickstart-Guide.mdx
- docs/Quickstart Guides/Matched-Audience-Upload-API-Quickstart-Guide.mdx
- docs/Quickstart Guides/Reporting-API-Quickstart-Guide.mdx
- docs/Quickstart Guides/Schedule-Report-API-Quickstart-Guide.mdx
- docs/Quickstart Guides/Upload-Creative-and-Create-a-Campaign-API-Quickstart-Guide.mdx
Shifts SVG icons to better align with text
> SVG alignment

- .gitignore
- docs/Guidelines/Bid-Model-API-Guidelines.mdx
- docs/Guidelines/Campaign-API-Guidelines.mdx
- docs/intro.mdx
- docusaurus.config.js
- package-lock.json
- package.json
- src/css/custom.css
Tables with objects now have nested tables for object properties
> Table rework

- docs/Getting Started/Before-You-Begin.mdx
- docs/Getting Started/REST-API-Reference.mdx
- docs/Getting Started/Typescript-Prerequisites.mdx
- docs/Getting Started/index.mdx
- docs/Guidelines/Bid-Model-API-Guidelines.mdx
- docs/Guidelines/Campaign-API-Guidelines.mdx
- docs/Guidelines/Conversion-API-Guidelines.mdx
- docs/Guidelines/Finance-Guidelines.mdx
- docs/Guidelines/Insights-API-Guidelines.mdx
- docs/Guidelines/Inventory-API-Guide.mdx
- docs/Guidelines/Master-API-Guidelines.mdx
- docs/Guidelines/Reports-API-Guidelines.mdx
- docs/Guidelines/User-Profile-Guidelines.mdx
- docs/Guidelines/Workspace-Guidelines.mdx
- docs/Guidelines/index.mdx
- docs/Quickstart Guides/Authentication-Quickstart-Guide.mdx
- docs/Quickstart Guides/Matched-Audience-Upload-API-Quickstart-Guide.mdx
- docs/Quickstart Guides/Reporting-API-Quickstart-Guide.mdx
- docs/Quickstart Guides/Schedule-Report-API-Quickstart-Guide.mdx
- docs/Quickstart Guides/Upload-Creative-and-Create-a-Campaign-API-Quickstart-Guide.mdx
- docs/Quickstart Guides/index.mdx
- docs/intro.mdx
- docusaurus.config.js
- sidebars.js
- src/css/custom.css
Adds Overview sections to each Guidelines Page, adding more information/context for each API
Updates Front Page to include more resources, links
Updates SVG icons
Other style changes
> Style updates 5

- .gitignore
- docs/Getting Started/Before-You-Begin.mdx
- docs/Getting Started/REST-API-Reference.mdx
- docs/Guidelines/Assets-API-Guidelines.mdx
- docs/Guidelines/Bid-Model-API-Guidelines.mdx
- docs/Guidelines/Campaign-API-Guidelines.mdx
- docs/Guidelines/Conversion-API-Guidelines.mdx
- docs/Guidelines/Finance-Guidelines.mdx
- docs/Guidelines/Insights-API-Guidelines.mdx
- docs/Guidelines/Inventory-API-Guide.mdx
- docs/Guidelines/Master-API-Guidelines.mdx
- docs/Guidelines/Reports-API-Guidelines.mdx
- docs/Guidelines/User-Profile-Guidelines.mdx
- docs/Guidelines/Workspace-Guidelines.mdx
- docs/Quickstart Guides/Authentication-Quickstart-Guide.mdx
- docs/Quickstart Guides/Matched-Audience-Upload-API-Quickstart-Guide.mdx
- docs/Quickstart Guides/Reporting-API-Quickstart-Guide.mdx
- docs/Quickstart Guides/Schedule-Report-API-Quickstart-Guide.mdx
- docs/Quickstart Guides/Upload-Creative-and-Create-a-Campaign-API-Quickstart-Guide.mdx
- src/css/custom.css
Adds accordion element to tables with nested object properties
Updates accordion style
Updates terminology: all instances of 'report' now lowercase
Updates all link labels for case consistency
> Style update 6

- docs/Guidelines/Assets-API-Guidelines.mdx
- docusaurus.config.js
- src/css/custom.css
Dark theme style update
Assets overview section
Config update
> Style update 7

- docs/Getting Started/Platform-overview.mdx
- docs/Guidelines/Finance-Guidelines.mdx
Adds links to API references in Platform Overview page
Adds more parameter definitions in Finance API
> Content update

- docs/Guidelines/Campaign-API-Guidelines.mdx
- sidebars.js
Adds v2 endpoint for creating a Campaign
> Campaign Guidelines

- docs/Getting Started/Typescript-Prerequisites.mdx
- docs/Guidelines/Assets-API-Guidelines.mdx
- docs/Guidelines/Bid-Model-API-Guidelines.mdx
- docs/Guidelines/Campaign-API-Guidelines.mdx
- docs/Guidelines/Conversion-API-Guidelines.mdx
- docs/Guidelines/Creative-API-Guidelines.mdx
- docs/Guidelines/Finance-Guidelines.mdx
- docs/Guidelines/Insights-API-Guidelines.mdx
- docs/Guidelines/Inventory-API-Guide.mdx
- docs/Guidelines/Master-API-Guidelines.mdx
- docs/Guidelines/Planner-API-Guidelines.mdx
- docs/Guidelines/Reports-API-Guidelines.mdx
- docs/Guidelines/User-Profile-Guidelines.mdx
- docs/Guidelines/Workspace-Guidelines.mdx
- docs/Quickstart Guides/Authentication-Quickstart-Guide.mdx
- docs/Quickstart Guides/Matched-Audience-Upload-API-Quickstart-Guide.mdx
- docs/Quickstart Guides/Reporting-API-Quickstart-Guide.mdx
- docs/Quickstart Guides/Schedule-Report-API-Quickstart-Guide.mdx
- docs/Quickstart Guides/Upload-Creative-and-Create-a-Campaign-API-Quickstart-Guide.mdx
- sidebars.js
changed parameters in description text from `code` to <var>code</var> so they have a grey background for improved readability
> Param styling

- docs/Tutorials/Trade Desk Migration/Campaign-Migration-Guide.mdx
- docs/Tutorials/Trade Desk Migration/Conversions-Migration-Guide.mdx
- docs/Tutorials/Trade Desk Migration/Inventories-Migration-Guide.mdx
- docs/Tutorials/Trade Desk Migration/Overview.mdx
Minor updates to migration pages
All instances of "pixel" and "postback" capitalized
> Terminology Consistency

- docs/Migration Guides/The Trade Desk/Bid-Model-Migration-Guide.mdx
- docs/Migration Guides/The Trade Desk/Campaign-Migration-Guide.mdx
- docs/Migration Guides/The Trade Desk/Conversions-Migration-Guide.mdx
- docs/Migration Guides/The Trade Desk/Inventories-Migration-Guide.mdx
- docs/Migration Guides/The Trade Desk/Overview.mdx
- docs/Migration Guides/The Trade Desk/Reports-Migration-Guide.mdx
- docs/Migration Guides/index.mdx
- docusaurus.config.js
- sidebars.js
- src/css/custom.css
Updates structure of migration docs for readability and organization
Clarifies language for descriptions and overview sections
> TTD Migration Docs

- docs/Getting Started/Typescript-Prerequisites.mdx
- docs/Getting Started/index.mdx
- docs/Migration Guides/Beeswax/Bid-Model-Migration.mdx
- docs/Migration Guides/Beeswax/Campaign-Migration-Guide.mdx
- docs/Migration Guides/Beeswax/Conversions-Migration.mdx
- docs/Migration Guides/Beeswax/Inventories-Migration.mdx
- docs/Migration Guides/Beeswax/Overview.mdx
- docs/Migration Guides/Beeswax/Reports-Migration.mdx
- docs/Migration Guides/The Trade Desk/Bid-Model-Migration-Guide.mdx
- docs/Migration Guides/The Trade Desk/Conversions-Migration-Guide.mdx
- docs/Migration Guides/The Trade Desk/Overview.mdx
- docs/Migration Guides/The Trade Desk/Reports-Migration-Guide.mdx
- docs/Migration Guides/index.mdx
- docs/Quickstart Guides/Schedule-Report-API-Quickstart-Guide.mdx
- docs/Quickstart Guides/index.mdx
- docs/intro.mdx
Second round of feedback changes
> TTD & Beeswax Updates

- docs/Getting Started/Before-You-Begin.mdx
- docs/Getting Started/Platform-overview.mdx
- docs/Getting Started/REST-API-Reference.mdx
- docs/Guidelines/Assets-API-Guidelines.mdx
- docs/Guidelines/Bid-Model-API-Guidelines.mdx
- docs/Guidelines/Campaign-API-Guidelines.mdx
- docs/Guidelines/Conversion-API-Guidelines.mdx
- docs/Guidelines/Creative-API-Guidelines.mdx
- docs/Guidelines/Finance-Guidelines.mdx
- docs/Guidelines/Insights-API-Guidelines.mdx
- docs/Guidelines/Inventory-API-Guide.mdx
- docs/Guidelines/Reports-API-Guidelines.mdx
- docs/Guidelines/User-Profile-Guidelines.mdx
- docs/Guidelines/Workspace-Guidelines.mdx
- docs/Guidelines/index.mdx
- docs/Migration Guides/Beeswax/Overview.mdx
- docs/Migration Guides/The Trade Desk/Overview.mdx
- docs/Migration Guides/Xandr/Overview.mdx
- docs/Quickstart Guides/Authentication-Quickstart-Guide.mdx
- docs/Quickstart Guides/Matched-Audience-Upload-API-Quickstart-Guide.mdx
- docs/Quickstart Guides/Reporting-API-Quickstart-Guide.mdx
- docs/Quickstart Guides/Schedule-Report-API-Quickstart-Guide.mdx
- docs/Quickstart Guides/Upload-Creative-and-Create-a-Campaign-API-Quickstart-Guide.mdx
- docs/intro.mdx
- src/css/custom.css
Updates content on Getting Started and Quickstart pages
Updates language to match marketing usage
Improves some tables' formatting/content
Improves some CSS styling
> Various updates

- docs/Guidelines/Audience-API-Guidelines.mdx
- docs/Guidelines/Finance-Guidelines.mdx
- sidebars.js
Adds new endpoints for DV-IVT Segments
> DV-IFT endpoints

- docs/Getting Started/Platform-overview.mdx
- docs/Guidelines/Audience-API-Guidelines.mdx
- docs/Guidelines/Campaign-API-Guidelines.mdx
- docs/Guidelines/Finance-Guidelines.mdx
- docs/Guidelines/Master-API-Guidelines.mdx
- docs/Guidelines/Reports-API-Guidelines.mdx
Adds missing TS samples to endpoints
> TypeScript samples

- docs/Guidelines/Insights-API-Guidelines.mdx
- sidebars.js
Reorganizes Insights endpoints
Adds overview descriptions of Insights types
Adds eligibility criteria descriptions
> Insights API reorg

- docs/Guidelines/Insights-API-Guidelines.mdx
- docs/Guidelines/Reports-API-Guidelines.mdx
- docs/Quickstart Guides/Matched-Audience-Upload-API-Quickstart-Guide.mdx
- docs/Quickstart Guides/Reporting-API-Quickstart-Guide.mdx
- docs/Quickstart Guides/Schedule-Report-API-Quickstart-Guide.mdx
- docs/Quickstart Guides/Upload-Creative-and-Create-a-Campaign-API-Quickstart-Guide.mdx
- docs/intro.mdx
Correction to Insights sections
Capitalizes all instances of Quickstart Guide for consistency
> Terminology

- docs/Getting Started/Before-You-Begin.mdx
- docs/Getting Started/REST-API-Reference.mdx
- docs/Guidelines/Audience-API-Guidelines.mdx
- docs/Guidelines/Campaign-API-Guidelines.mdx
- docs/Guidelines/Insights-API-Guidelines.mdx
- docs/Quickstart Guides/Insights-Quickstart.mdx
- docs/Quickstart Guides/Matched-Audience-Upload-API-Quickstart-Guide.mdx
- docs/Quickstart Guides/Schedule-Report-API-Quickstart-Guide.mdx
- docs/Quickstart Guides/Upload-Creative-and-Create-a-Campaign-API-Quickstart-Guide.mdx
- docs/Quickstart Guides/index.mdx
- sidebars.js
Adds Insights Quickstart Guide page
Adds one missing endpoint to Campaign API
Corrects info on Getting Started page
> Insights quickstart guide

- docs/Getting Started/index.mdx
- docs/Guidelines/API-JSON-File.mdx
Adds Pagination card to index
Removes previous page button for OpenAPI spec download page
> Format updates

- docs/Guidelines/Finance-Guidelines.mdx
- docs/Guidelines/Insights-API-Guidelines.mdx
- sidebars.js
Adds all SLS endpoints to Insights API and Finance API
> Insights/Finance SLS endpoints

- docs/Quickstart Guides/Bid-Model-Quickstart.mdx
- docs/Quickstart Guides/Insights-Quickstart.mdx
- docs/Quickstart Guides/Inventory-Quickstart.mdx
- docs/Quickstart Guides/Matched-Audience-Upload-API-Quickstart-Guide.mdx
- docs/Tutorials/index.mdx
- docusaurus.config.js
- sidebars.js
Updates URL slugs for Tutorial pages
Adds redirects for old URLs
> URLs and Redirects

- docs/Guidelines/Audience-API-Guidelines.mdx
- docs/Quickstart Guides/Contextual-Audience-Quickstart.mdx
- docs/Quickstart Guides/index.mdx
- sidebars.js
Adds Contextual Audience Quickstart Guide
Adds sidebar items
Adds Index card
Updates Audience API
> Contextual audience quickstart

- docs/Guidelines/Campaign-API-Guidelines.mdx
- sidebars.js
Adds endpoint for deals associated with Campaigns
> Campaign API

- docs/Guidelines/Assets-API-Guidelines.mdx
- docs/Guidelines/Audience-API-Guidelines.mdx
- docs/Guidelines/Dashboard-API-Guidelines.mdx
- docs/Guidelines/Reports-API-Guidelines.mdx
- docs/Healthcare Vertical/Audience-Healthcare.mdx
- docs/Political Vertical/Audience-Segments.mdx
- docs/Quickstart Guides/Matched-Audience-Upload-API-Quickstart-Guide.mdx
Updates parameters definitions
> Parameters definitions

- docs/Guidelines/Assets-API-Guidelines.mdx
- docs/Guidelines/Audience-API-Guidelines.mdx
- docs/Guidelines/Bid-Model-API-Guidelines.mdx
- docs/Guidelines/Campaign-API-Guidelines.mdx
- docs/Guidelines/Conversion-API-Guidelines.mdx
- docs/Guidelines/Creative-API-Guidelines.mdx
- docs/Guidelines/Finance-Guidelines.mdx
- docs/Guidelines/Insights-API-Guidelines.mdx
- docs/Guidelines/Planner-API-Guidelines.mdx
- docs/Guidelines/Reports-API-Guidelines.mdx
- docs/Healthcare Vertical/Audience-Healthcare.mdx
- docs/Healthcare Vertical/Insights-PLD.mdx
- docs/Political Vertical/Audience-Segments.mdx
- docs/Quickstart Guides/Conversion-Quickstart.mdx
- docs/Quickstart Guides/Upload-a-Creative-Quickstart.mdx
- sidebars.js
Standardizes "required" parameters
Updates some parameter tables and descriptions
Adds, fixes, and updates various links
> Required params standardization

- docs/Getting Started/API-Pagination-Guide.mdx
- docs/Getting Started/REST-API-Reference.mdx
- sidebars.js
- src/css/custom.css
Updates Filtering and Pagination page
Adds GET, POST, PUT/PATCH, DELETE sections to API Overview page
> Getting Started updates

- docs/Guidelines/Audience-API-Guidelines.mdx
- docs/Guidelines/Bid-Model-API-Guidelines.mdx
- docs/Guidelines/Finance-Guidelines.mdx
- docs/Guidelines/Insights-API-Guidelines.mdx
- docs/Guidelines/Master-API-Guidelines.mdx
- docs/Guidelines/Workspace-Guidelines.mdx
- docs/Tutorials/Customer-Guide.mdx
Updates filtering and pagination parameters for the Master API
Updates parameters tables crosslinks in all guidelines pages
> Guidelines updates

- docs/Guidelines/Conversion-API-Guidelines.mdx
- docs/Guidelines/Dashboard-API-Guidelines.mdx
- docs/Guidelines/Reports-API-Guidelines.mdx
- docs/Guidelines/Workspace-Guidelines.mdx
- sidebars.js
Adds new button to relevant sections
Moves one section in Workspace API
> Resource Properties Buttons

- docs/Getting Started/Before-You-Begin.mdx
- docs/Guidelines/Audience-API-Guidelines.mdx
- docs/Guidelines/User-Profile-Guidelines.mdx
- docs/Quickstart Guides/Authentication-Quickstart-Guide.mdx
- src/css/custom.css
Updates authentication quickstart with Client ID and Client Secret description
Updates sign up and log in endpoints authentication description
Updates some links and typos
Updates header 4 color in css and fixes a table of contents issue in dark theme
> Authentication Updates

- docs/Healthcare Vertical/Insights-PLD.mdx
- docs/Political Vertical/Insights-VLD.mdx
Updates Insights Guidelines pages for Healthcare and Political verticals
> Insights updates
